apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hrnrx9o90-nodejs 
  janus-idp.io/tekton: hrnrx9o90-nodejs
  backstage.io/kubernetes-id: hrnrx9o90-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hrnrx9o90-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml